### ISSUE TITLE
How to Install Plugins on Your Minecraft Server

### ISSUE THREAD

**Issue by parkersawh** [Crazys-Corner/CivilHost-Community-Content#1]
<div class="OutlineElement Ltr SCXW135692401 BCX0">
<p class="Paragraph SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">How to Install Plugins on Your Minecraft Server</span></span><span class="EOP SCXW135692401 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;335559685&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW135692401 BCX0">
<p class="Paragraph SCXW135692401 BCX0"><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">Before you get started, make sure your Minecraft server is running a supported server type for plugins, such as&nbsp;</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">Paper</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> or&nbsp;</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">CraftBukkit</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> for Minecraft Java Edition.</span><span class="NormalTextRun SCXW135692401 BCX0"> [insert image of change server type dropdown]</span><span class="NormalTextRun SCXW135692401 BCX0"> to install plugins manually, navigate to your control panel </span><span class="NormalTextRun SCXW135692401 BCX0">[here](https://www.contr</span><span class="NormalTextRun SCXW135692401 BCX0">ol.civilhost.net)</span><span class="NormalTextRun SCXW135692401 BCX0">. </span><span class="NormalTextRun SCXW135692401 BCX0">Once navigated to your </span><span class="NormalTextRun SCXW135692401 BCX0">CivilHost Control Panel</span><span class="NormalTextRun SCXW135692401 BCX0">, download a .jar from a trusted source such as [SpigotMC](</span><span class="NormalTextRun SCXW135692401 BCX0">https://www.spigotmc.org/resources/categories/spigot.4</span><span class="NormalTextRun SCXW135692401 BCX0">) or </span><span class="NormalTextRun SCXW135692401 BCX0">[</span><span class="NormalTextRun SCXW135692401 BCX0">Bukkit</span><span class="NormalTextRun SCXW135692401 BCX0">](https://dev.bukkit.org/bukkit-plugins]</span> <span class="NormalTextRun SCXW135692401 BCX0">Find a plugin you like, such as [</span><span class="NormalTextRun SCXW135692401 BCX0">EssentialsX</span><span class="NormalTextRun SCXW135692401 BCX0">](https://www.spigotmc.org/resources/essentialsx.9089)</span><span class="NormalTextRun SCXW135692401 BCX0">. Once </span><span class="NormalTextRun SCXW135692401 BCX0">you have</span><span class="NormalTextRun SCXW135692401 BCX0"> successfully downloaded a plugin, you should have a .jar file in your downloads folder.&nbsp;</span><span class="NormalTextRun SCXW135692401 BCX0">Next, go back to your CivilHost Control Pane</span><span class="NormalTextRun SCXW135692401 BCX0">l. Now you need to navigate to /plugins. To do this, </span><span class="NormalTextRun SCXW135692401 BCX0">click </span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">Files</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> above your console, then click the plugins folder. To upload the plugin(s) from your computer to your CivilHost Minecraft Server, </span><span class="NormalTextRun SCXW135692401 BCX0">click on the upload button and select your .jar file(s) you downloaded earlier and click open! </span><span class="NormalTextRun SCXW135692401 BCX0">Start your </span><span class="NormalTextRun SCXW135692401 BCX0">server. </span><span class="NormalTextRun SCXW135692401 BCX0">You&rsquo;re</span><span class="NormalTextRun SCXW135692401 BCX0"> done! Some plugins will generate configuration files found in /plugins/&lt;</span><span class="NormalTextRun SCXW135692401 BCX0">plugin_name</span><span class="NormalTextRun SCXW135692401 BCX0">&gt; folders, allowing you to change </span><span class="NormalTextRun SCXW135692401 BCX0">their behavior. To ensure that the plugins were installed successfully, type in </span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">/plugins</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> in game or </span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">plugins</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> in your server&rsquo;s console. If you need any further aid, contact CivilHost </span><span class="NormalTextRun SCXW135692401 BCX0">by emailing </span></span><a class="Hyperlink SCXW135692401 BCX0" href="mailto:support@civilhost.net" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW135692401 BCX0" data-ccp-charstyle="Hyperlink">support@civilhost.net</span></span></a><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">. </span></span><span class="EOP SCXW135692401 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559731&quot;:720,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>

**Comment by Crazys-Corner** [comment]
We need the HTML, not raw text.

**Comment by parkersawh** [comment]
<div class="OutlineElement Ltr SCXW135692401 BCX0">
<p class="Paragraph SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">How to Install Plugins on Your Minecraft Server</span></span><span class="EOP SCXW135692401 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;335559685&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW135692401 BCX0">
<p class="Paragraph SCXW135692401 BCX0"><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">Before you get started, make sure your Minecraft server is running a supported server type for plugins, such as&nbsp;</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">Paper</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> or&nbsp;</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">CraftBukkit</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> for Minecraft Java Edition.</span><span class="NormalTextRun SCXW135692401 BCX0"> [insert image of change server type dropdown]</span><span class="NormalTextRun SCXW135692401 BCX0"> to install plugins manually, navigate to your control panel </span><span class="NormalTextRun SCXW135692401 BCX0">[here](https://www.contr</span><span class="NormalTextRun SCXW135692401 BCX0">ol.civilhost.net)</span><span class="NormalTextRun SCXW135692401 BCX0">. </span><span class="NormalTextRun SCXW135692401 BCX0">Once navigated to your </span><span class="NormalTextRun SCXW135692401 BCX0">CivilHost Control Panel</span><span class="NormalTextRun SCXW135692401 BCX0">, download a .jar from a trusted source such as [SpigotMC](</span><span class="NormalTextRun SCXW135692401 BCX0">https://www.spigotmc.org/resources/categories/spigot.4</span><span class="NormalTextRun SCXW135692401 BCX0">) or </span><span class="NormalTextRun SCXW135692401 BCX0">[</span><span class="NormalTextRun SCXW135692401 BCX0">Bukkit</span><span class="NormalTextRun SCXW135692401 BCX0">](https://dev.bukkit.org/bukkit-plugins]</span> <span class="NormalTextRun SCXW135692401 BCX0">Find a plugin you like, such as [</span><span class="NormalTextRun SCXW135692401 BCX0">EssentialsX</span><span class="NormalTextRun SCXW135692401 BCX0">](https://www.spigotmc.org/resources/essentialsx.9089)</span><span class="NormalTextRun SCXW135692401 BCX0">. Once </span><span class="NormalTextRun SCXW135692401 BCX0">you have</span><span class="NormalTextRun SCXW135692401 BCX0"> successfully downloaded a plugin, you should have a .jar file in your downloads folder.&nbsp;</span><span class="NormalTextRun SCXW135692401 BCX0">Next, go back to your CivilHost Control Pane</span><span class="NormalTextRun SCXW135692401 BCX0">l. Now you need to navigate to /plugins. To do this, </span><span class="NormalTextRun SCXW135692401 BCX0">click </span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">Files</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> above your console, then click the plugins folder. To upload the plugin(s) from your computer to your CivilHost Minecraft Server, </span><span class="NormalTextRun SCXW135692401 BCX0">click on the upload button and select your .jar file(s) you downloaded earlier and click open! </span><span class="NormalTextRun SCXW135692401 BCX0">Start your </span><span class="NormalTextRun SCXW135692401 BCX0">server. </span><span class="NormalTextRun SCXW135692401 BCX0">You&rsquo;re</span><span class="NormalTextRun SCXW135692401 BCX0"> done! Some plugins will generate configuration files found in /plugins/&lt;</span><span class="NormalTextRun SCXW135692401 BCX0">plugin_name</span><span class="NormalTextRun SCXW135692401 BCX0">&gt; folders, allowing you to change </span><span class="NormalTextRun SCXW135692401 BCX0">their behavior. To ensure that the plugins were installed successfully, type in </span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">/plugins</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> in game or </span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">plugins</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> in your server&rsquo;s console. If you need any further aid, contact CivilHost </span><span class="NormalTextRun SCXW135692401 BCX0">by emailing </span></span><a class="Hyperlink SCXW135692401 BCX0" href="mailto:support@civilhost.net" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW135692401 BCX0" data-ccp-charstyle="Hyperlink">support@civilhost.net</span></span></a><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">. </span></span><span class="EOP SCXW135692401 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559731&quot;:720,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>

**Comment by parkersawh** [comment]
`<div class="OutlineElement Ltr SCXW135692401 BCX0">
<p class="Paragraph SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">How to Install Plugins on Your Minecraft Server</span></span><span class="EOP SCXW135692401 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;335559685&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW135692401 BCX0">
<p class="Paragraph SCXW135692401 BCX0"><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">Before you get started, make sure your Minecraft server is running a supported server type for plugins, such as&nbsp;</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">Paper</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> or&nbsp;</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">CraftBukkit</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> for Minecraft Java Edition.</span><span class="NormalTextRun SCXW135692401 BCX0"> [insert image of change server type dropdown]</span><span class="NormalTextRun SCXW135692401 BCX0"> to install plugins manually, navigate to your control panel </span><span class="NormalTextRun SCXW135692401 BCX0">[here](https://www.contr</span><span class="NormalTextRun SCXW135692401 BCX0">ol.civilhost.net)</span><span class="NormalTextRun SCXW135692401 BCX0">. </span><span class="NormalTextRun SCXW135692401 BCX0">Once navigated to your </span><span class="NormalTextRun SCXW135692401 BCX0">CivilHost Control Panel</span><span class="NormalTextRun SCXW135692401 BCX0">, download a .jar from a trusted source such as [SpigotMC](</span><span class="NormalTextRun SCXW135692401 BCX0">https://www.spigotmc.org/resources/categories/spigot.4</span><span class="NormalTextRun SCXW135692401 BCX0">) or </span><span class="NormalTextRun SCXW135692401 BCX0">[</span><span class="NormalTextRun SCXW135692401 BCX0">Bukkit</span><span class="NormalTextRun SCXW135692401 BCX0">](https://dev.bukkit.org/bukkit-plugins]</span> <span class="NormalTextRun SCXW135692401 BCX0">Find a plugin you like, such as [</span><span class="NormalTextRun SCXW135692401 BCX0">EssentialsX</span><span class="NormalTextRun SCXW135692401 BCX0">](https://www.spigotmc.org/resources/essentialsx.9089)</span><span class="NormalTextRun SCXW135692401 BCX0">. Once </span><span class="NormalTextRun SCXW135692401 BCX0">you have</span><span class="NormalTextRun SCXW135692401 BCX0"> successfully downloaded a plugin, you should have a .jar file in your downloads folder.&nbsp;</span><span class="NormalTextRun SCXW135692401 BCX0">Next, go back to your CivilHost Control Pane</span><span class="NormalTextRun SCXW135692401 BCX0">l. Now you need to navigate to /plugins. To do this, </span><span class="NormalTextRun SCXW135692401 BCX0">click </span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">Files</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> above your console, then click the plugins folder. To upload the plugin(s) from your computer to your CivilHost Minecraft Server, </span><span class="NormalTextRun SCXW135692401 BCX0">click on the upload button and select your .jar file(s) you downloaded earlier and click open! </span><span class="NormalTextRun SCXW135692401 BCX0">Start your </span><span class="NormalTextRun SCXW135692401 BCX0">server. </span><span class="NormalTextRun SCXW135692401 BCX0">You&rsquo;re</span><span class="NormalTextRun SCXW135692401 BCX0"> done! Some plugins will generate configuration files found in /plugins/&lt;</span><span class="NormalTextRun SCXW135692401 BCX0">plugin_name</span><span class="NormalTextRun SCXW135692401 BCX0">&gt; folders, allowing you to change </span><span class="NormalTextRun SCXW135692401 BCX0">their behavior. To ensure that the plugins were installed successfully, type in </span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">/plugins</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> in game or </span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">plugins</span></span><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0"> in your server&rsquo;s console. If you need any further aid, contact CivilHost </span><span class="NormalTextRun SCXW135692401 BCX0">by emailing </span></span><a class="Hyperlink SCXW135692401 BCX0" href="mailto:support@civilhost.net" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW135692401 BCX0" data-ccp-charstyle="Hyperlink">support@civilhost.net</span></span></a><span class="TextRun SCXW135692401 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW135692401 BCX0">. </span></span><span class="EOP SCXW135692401 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559731&quot;:720,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>`

**Comment by Crazys-Corner** [comment]
![image](https://github.com/Crazys-Corner/CivilHost-Community-Content/assets/97609827/e932369c-383d-40d4-aad0-e111e3f55f6d)

Lack of formatting, needs more formatting before release. 👎

**Comment by parkersawh** [comment]
<div class="OutlineElement Ltr SCXW184578934 BCX0">
<p>Before you get started, make sure your Minecraft server is running a supported server type for plugins, such as Paper or CraftBukkit for Minecraft Java Edition. (Refer to the image for changing the server type dropdown.) To install plugins manually, navigate to your control panel <a href="https://www.control.civilhost.net/" target="_new">here</a>.</p>
<p>Once on your CivilHost Control Panel, download a .jar from a trusted source like <a href="https://www.spigotmc.org/resources/categories/spigot.4" target="_new">SpigotMC</a> or <a href="https://dev.bukkit.org/bukkit-plugins" target="_new">Bukkit</a>. Find a plugin you like, such as <a href="https://www.spigotmc.org/resources/essentialsx.9089" target="_new">EssentialsX</a>. After successfully downloading a plugin, you should have a .jar file in your downloads folder.</p>
<p>Next, return to your CivilHost Control Panel. Navigate to /plugins by clicking "Files" above your console and then selecting the "plugins" folder. To upload the plugin(s) from your computer to your CivilHost Minecraft Server, click on the upload button and select the .jar file(s) you downloaded earlier, then click "Open".</p>
<p>Start your server, and you&rsquo;re done! Some plugins will generate configuration files found in /plugins/&lt;plugin_name&gt; folders, allowing you to change their behavior. To ensure the successful installation of the plugins, type in "/plugins" in-game or "plugins" in your server&rsquo;s console. For further assistance, contact CivilHost by emailing <a href="mailto:support@civilhost.net" target="_new">support@civilhost.net</a>.</p>
</div>

**Comment by Crazys-Corner** [comment]
👍 
Sent to review for Silent, he'll let you know any final details.

**Comment by SilentAssassin101** [comment]
looks good @Crazys-Corner

**Comment by Crazys-Corner** [comment]
Closed, please email Crazy@CivilHost.net with the email used to sign up for your billing account to receive $5 in credit.
