### ISSUE TITLE
How to install ForgeMC and install Mods

### ISSUE THREAD

**Issue by parkersawh** [Crazys-Corner/CivilHost-Community-Content#2]
<div class="OutlineElement Ltr SCXW94674220 BCX0">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Forge is one of Minecraft&rsquo;s most popular mod loaders, featuring thousands of mods that have added content to Minecraft for each version of the game. If you would like to use Forge Mods on your server, you must install the same version of Forge on both your CivilHost Minecraft and your Minecraft Game client.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559731&quot;:720,&quot;335559738&quot;:240,&quot;335559739&quot;:240,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW94674220 BCX0">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Before installing mods, you need to know what Forge version you want to use. This will, of course, depend on what Minecraft version your mods/</span><span class="NormalTextRun SCXW94674220 BCX0">modpacks</span><span class="NormalTextRun SCXW94674220 BCX0"> will use. To join your Forge Minecraft server, you must also have the forge client running on your computer while you are playing.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559731&quot;:720,&quot;335559738&quot;:240,&quot;335559739&quot;:240,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW94674220 BCX0">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" style="text-align: center;" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Automatic Forge Installation:</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;335559738&quot;:240,&quot;335559739&quot;:240,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="1">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">CivilHost supports a variety of game versions, ranging from 1.5.2 to the latest game version, 1.20.1. If we </span><span class="NormalTextRun SCXW94674220 BCX0">don&rsquo;t</span><span class="NormalTextRun SCXW94674220 BCX0"> have a version that you would like added, please make a ticket </span></span><a class="Hyperlink SCXW94674220 BCX0" href="https://civilhost.net/hosting/submitticket.php" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW94674220 BCX0" data-ccp-charstyle="Hyperlink">here</span></span></a><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0"> so we can add the specified game version of your liking.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="2">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Stop your server.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="3">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="3" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Go to your CivilHost control panel </span></span><a class="Hyperlink SCXW94674220 BCX0" href="https://www.control.civilhost.net/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW94674220 BCX0" data-ccp-charstyle="Hyperlink">here</span></span></a><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="4">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="4" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">At the top of the page, click Version.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="5">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="5" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">In the version selector tab, click Forge.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="6">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="6" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Find the version you want to install on your server, then click install.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="7">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="7" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Click INSTALL; keep in mind, this will remove all libraries and configuration files from your server.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="8">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="8" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Start your server.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="9">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="9" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">If required, accept the Minecraft </span></span><a class="Hyperlink SCXW94674220 BCX0" href="https://www.minecraft.net/en-us/eula" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW94674220 BCX0" data-ccp-charstyle="Hyperlink">EULA</span></span></a><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="10">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="10" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Once your server has successfully started, find mods/</span><span class="NormalTextRun SCXW94674220 BCX0">modpacks</span><span class="NormalTextRun SCXW94674220 BCX0"> at a trusted source such as </span></span><a class="Hyperlink SCXW94674220 BCX0" href="https://www.curseforge.com/minecraft/search?page=1&amp;pageSize=20&amp;sortType=1&amp;class=mc-mods" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW94674220 BCX0" data-ccp-charstyle="Hyperlink">CurseForge</span></span></a><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="11">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="11" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">After downloading the mod of your choosing, on your CivilHost Control Panel, click Files at the top of your screen, then click the mods folder.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="12">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="12" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Drag and drop the selected mods from your computer.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW94674220 BCX0">
<ol class="NumberListStyle1 SCXW94674220 BCX0" role="list" start="13">
<li class="OutlineElement Ltr SCXW94674220 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="13" data-aria-level="1">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">Restart your server.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW94674220 BCX0">
<p class="Paragraph SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">You have now successfully installed mods and or </span><span class="NormalTextRun SCXW94674220 BCX0">modpacks</span><span class="NormalTextRun SCXW94674220 BCX0"> on your CivilHost Minecraft server, congratulations! If you run into any issues, please feel free to make a ticket </span></span><a class="Hyperlink SCXW94674220 BCX0" href="https://civilhost.net/hosting/submitticket.php" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW94674220 BCX0" data-ccp-charstyle="Hyperlink">here</span></span></a><span class="TextRun SCXW94674220 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW94674220 BCX0">.</span></span><span class="EOP SCXW94674220 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559731&quot;:720,&quot;335559738&quot;:240,&quot;335559739&quot;:240,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>

**Comment by SilentAssassin101** [comment]
nice

**Comment by Crazys-Corner** [comment]
Accepted 👍 

Please email Crazy@CivilHost.net with the email used to sign up for your billing account to receive $10 in credit.
