### ISSUE TITLE
How to install and configure GeyserMC for your CivilHost Minecraft Server

### ISSUE THREAD

**Issue by parkersawh** [Crazys-Corner/CivilHost-Community-Content#3]
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0"> is a proxy for Minecraft that allows Bedrock edition players to join Java edition servers.</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0"> is a proxy, meaning worlds and </span><span class="NormalTextRun SCXW8038230 BCX0">playerdata</span><span class="NormalTextRun SCXW8038230 BCX0"> cannot exist on </span><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0">. </span><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0"> was built to bridge the connection between Bedrock and Minecraft Java Editon. </span><span class="NormalTextRun SCXW8038230 BCX0">This is to prevent the need for two servers. </span><span class="NormalTextRun SCXW8038230 BCX0">CivilHost</span><span class="NormalTextRun SCXW8038230 BCX0"> recommends this as it is the easiest way to </span><span class="NormalTextRun SCXW8038230 BCX0">set up</span> <span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0">.</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">What Bedrock clients can connect?</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">The following client(s) can connect to your Minecraft server:</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="1">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Minecraft for Windows 10</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="2">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Minecraft Pocket Editon for IOS and Android devices</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="3">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="3" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Kindle Fire</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="4">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="3" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="4" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Fire TV</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Installing </span><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:0,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">The quickest way to install </span><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0"> for your CivilHost Minecraft server is to install it as a plugin.</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:0,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="1">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="2" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Download the latest version of </span><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0"> [here</span><span class="NormalTextRun SCXW8038230 BCX0">](</span><span class="NormalTextRun SCXW8038230 BCX0">https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/) </span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="2">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="2" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Go to your [control </span><span class="NormalTextRun SCXW8038230 BCX0">panel](</span><span class="NormalTextRun SCXW8038230 BCX0">https://control.civilhost.net) and STOP your server</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="3">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="2" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="3" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">At the top of your screen, navigate to </span></span><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Files</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="4">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="2" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="4" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Locate and open the </span></span><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">plugins</span></span><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0"> folder</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="5">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="2" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="5" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Drag and drop your </span><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0"> plugin from your downloads folder</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="6">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="2" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="6" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Return to the </span></span><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Console</span></span><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0"> tab and start your server</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW8038230 BCX0">
<ol class="NumberListStyle1 SCXW8038230 BCX0" role="list" start="7">
<li class="OutlineElement Ltr SCXW8038230 BCX0" role="listitem" data-leveltext="%1." data-font="Calibri" data-listid="2" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559683&quot;:0,&quot;335559684&quot;:-1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0,46],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" aria-setsize="-1" data-aria-posinset="7" data-aria-level="1">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Test your bedrock connection with the following command &ldquo;geyser </span><span class="NormalTextRun SCXW8038230 BCX0">connectiontest</span> <span class="NormalTextRun SCXW8038230 BCX0">IP:PORT</span><span class="NormalTextRun SCXW8038230 BCX0">&rdquo;</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Your </span><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0"> configuration should automatically adjust to your Minecraft server&rsquo;s IP and Port</span><span class="NormalTextRun SCXW8038230 BCX0">, if the connection happens to fail, check the </span><span class="NormalTextRun SCXW8038230 BCX0">config.yml</span><span class="NormalTextRun SCXW8038230 BCX0"> file </span><span class="NormalTextRun SCXW8038230 BCX0">found </span><span class="NormalTextRun SCXW8038230 BCX0">in /plugins/</span><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0">/</span><span class="NormalTextRun SCXW8038230 BCX0">config.yml</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:0,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Congratulations! Your Bedrock players should now be able to successfully connect to your </span><span class="NormalTextRun SCXW8038230 BCX0">Minecraft</span><span class="NormalTextRun SCXW8038230 BCX0"> server using </span><span class="NormalTextRun SCXW8038230 BCX0">GeyserMC</span><span class="NormalTextRun SCXW8038230 BCX0">!</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:0,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">If you run into any issues with the following setup, please do not hesitate to open a ticket [here](https://civilhost.net/hosting/submitticket.php).</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:0,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:0,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="TextRun SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8038230 BCX0">Article written by rooveinnit</span></span><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:0,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8038230 BCX0">
<p class="Paragraph SCXW8038230 BCX0" lang="EN-US" xml:lang="EN-US"><span class="EOP SCXW8038230 BCX0" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:0,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<p>&nbsp;</p>

**Comment by SilentAssassin101** [comment]
https://wiki.geysermc.org/geyser/setup/
explain that the server owner will need to get a second port for geyser and edit the config

**Comment by Crazys-Corner** [comment]
Closed due to inactivity.
