### ISSUE TITLE
How to set a server logo for your Minecraft Java server

### ISSUE THREAD

**Issue by PARTRIDGEMAN** [Crazys-Corner/CivilHost-Community-Content#6]
n/a

**Comment by Crazys-Corner** [comment]
Submitted for review @SilentAssassin101

**Comment by SilentAssassin101** [comment]
please update for mac compat

**Comment by PARTRIDGEMAN** [comment]
> please update for mac compat

Hi, I do not own any MacBooks and am unfamiliar with the process to change a file name on MacOS. Because of these factors I am unable to provide and screenshots

**Comment by SilentAssassin101** [comment]
look it up

**Comment by SilentAssassin101** [comment]
https://www.google.com

**Comment by PARTRIDGEMAN** [comment]
Not interested in adding macos support for this tut
